/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'rgb(var(--primary) / <alpha-value>)',
        secondary: 'rgb(var(--secondary) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        mainBackground: 'rgb(var(--main-background) / <alpha-value>)',
        mainText: 'rgb(var(--main-text) / <alpha-value>)',
        mutedText: 'rgb(var(--muted-text) / <alpha-value>)',
        success: 'rgb(var(--success) / <alpha-value>)',
        card: 'rgb(var(--card) / <alpha-value>)',
        oceanTint: 'rgb(var(--ocean-tint) / <alpha-value>)',
        gold: 'rgb(var(--accent) / <alpha-value>)',
        page: 'var(--bg-page)',
        section1: 'var(--bg-section-1)',
        section2: 'var(--bg-section-2)',
        lavender: 'var(--card-lavender)',
        cardDark: 'var(--card-dark)',
        cardWhite: 'var(--card-white)',
        textDark: 'var(--text-main)',
        textMute: 'var(--text-muted)',
        textLight: 'var(--text-light)',
        purple: 'var(--accent-purple)',
        purpleDeep: 'var(--accent-purple-deep)',
        purpleSoft: 'var(--accent-purple-soft)',
        subtle: 'var(--border-subtle)',
        resultNavy: 'var(--btn-result-navy)',
        navyHover: 'var(--btn-navy-hover)',
      },
      fontFamily: {
        poppins: ['Sora', 'sans-serif'],
        inter: ['Sora', 'sans-serif'],
        display: ['Sora', 'sans-serif'],
        playfair: ['Sora', 'sans-serif'],
        brand: ['Sora', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
